config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'static_pages#top'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'contact_form', to: 'static_pages#contact_form'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'dashboard', to: 'dashboards#top'

  resources :users, only: %i[new create]
  resource :account, only: %i[show edit update destroy]

  resources :colors, only: %i[index show] do
    collection do
      get :favorites
    end
    collection do
      get :all_ranks
    end
    collection do
      get :my_ranks
    end
  end
  resources :quizzes, only: %i[index] do
    resources :incorrect_answers, only: %i[create update]
    resources :correct_answers, only: %i[create]
    collection do
      get :is_spring
    end
    collection do
      get :is_summer
    end
    collection do
      get :is_autumn
    end
    collection do
      get :is_winter
    end
    collection do
      get :base
    end
    collection do
      get :mistakes
    end
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]
  resources :trials, only: %i[index] 
  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users
    resources :colors
  end
end

app/views/shared/_after_login_header.html.erb
<header class="after_login">
  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <!-- ブランドロゴここから -->
      <div id="after_lgoin_header_logo">
        <%= link_to dashboard_path, class: "navbar-brand text-white" do %>
          <%= image_tag 'brand_logo_w.png', class: "header_logo_size" %>
        <% end %>
      </div>
      <!-- ブランドロゴここまで -->
      <!-- ハンバーガーメニューここから -->
      <div class="openbtn1"><span></span><span></span><span></span></div>
        <nav id="g-nav">
          <div id="g-nav-list"><!--ナビの数が増えた場合縦スクロールするためのdiv※不要なら削除-->
            <ul>
              <li>
                <%= link_to dashboard_path, class: "d-flex align-items-center mb-4" do %>
                  ダッシュボード
                <% end %>
              </li>  
              <li>
                <%= link_to account_path, class: "d-flex align-items-center mb-4" do %>
                    アカウント設定
                  <% end %>
              </li>  
              <li>
                <%= link_to logout_path, class: "d-flex align-items-center mb-4", method: :delete do %>
                  ログアウト
                <% end %>
              </li>  
            </ul>
          </div>
        </nav>
      <!-- ハンバーガーメニューここまで -->
    </div><!-- /.container-fluid -->
  </nav>
</header>
<%= javascript_pack_tag 'header' %>


    

app/views/shared/_before_login_header.html.erb
<header class="before_login">
    <nav class="navbar navbar-light">
        <div class="container-fluid">
            <%= link_to root_path, class: "navbar-brand text-white" do %>
                <%= image_tag 'brand_logo_w.png', class: "header_logo_size" %>
            <% end %>
            <div class="d-flex justify-content-end align-items-center">
              <%= link_to (t 'defaults.login'), login_path, class: "loginbtn me-2 " %>
              <%= link_to "無料会員登録", new_user_path, class: "signupbtn me-1" %>
            </div>
        </div>
    </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger_error">
    <ul class="mb-0 none_dot">
      <% object.errors.full_messages.each do |msg| %>
        <li><i class="fas fa-exclamation-triangle me-1"></i><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> border-0 text-center py-3 rounded-0"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <hr class="my-4 mt-5">
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="col-lg-10 col-md-10 py-8">
        <div class="d-flex flex-column bd-highlight mb-3">
          <div class="p-2 bd-highlight">
            <%= image_tag 'brand_logo_g.png', class: "footer_logo_size" %>
          </div>
          <div class="p-2 bd-highlight">
            <%= link_to '利用規約', terms_of_service_path, class: "footer_link ms-1" %>
          </div>
          <div class="p-2 bd-highlight">
            <%= link_to 'プライバシーポリシー', privacy_policy_path, class: "footer_link ms-1" %>
          </div>
          <div class="p-2 bd-highlight">
            <%= link_to 'お問合せ', contact_form_path, class: "footer_link ms-1" %>
          </div>
          <div class="p-2 bd-highlight">
            <span class="footer_link">© 2023 mirume.All rights reserved.</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_root_floating_btn.html.erb
<div class="fixed_button container-fluid d-flex justify-content-center align-items-center">
        <%= link_to new_user_path, class: "btn text-white" do %>
            <span class="cta_label">無料会員登録</span>
        <% end %>    
</div>