config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'static_pages#top'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'contact_form', to: 'static_pages#contact_form'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'dashboard', to: 'dashboards#top'

  resources :users, only: %i[new create]
  resource :account, only: %i[show edit update destroy]

  resources :colors, only: %i[index show] do
    collection do
      get :favorites
    end
    collection do
      get :all_ranks
    end
    collection do
      get :my_ranks
    end
  end
  resources :quizzes, only: %i[index] do
    resources :incorrect_answers, only: %i[create update]
    resources :correct_answers, only: %i[create]
    collection do
      get :is_spring
    end
    collection do
      get :is_summer
    end
    collection do
      get :is_autumn
    end
    collection do
      get :is_winter
    end
    collection do
      get :base
    end
    collection do
      get :mistakes
    end
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]
  resources :trials, only: %i[index] 
  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users
    resources :colors
  end
end

app/models/color.rb
class Color < ApplicationRecord
  belongs_to :category
  has_many :quizzes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :code, presence: true, uniqueness: true
  validates :css_class, presence: true, uniqueness: true

  enum season_type: { uncategorized: 0, spring: 1, summer: 2, autumn: 3, winter: 4 }
end

app/controllers/admin/colors_controller.rb
class Admin::ColorsController < Admin::BaseController
  before_action :set_color, only: %i[edit show update destroy]
  
  def index
    @colors = Color.all.order(created_at: :asc)
  end

  def show; end

  def edit; end

  def update
    if @color.update(color_params)
      redirect_to admin_colors_path, success: 'Color was successfully updated.'
    else
      flash.now['danger'] = 'Color update failed.'
      render :edit
    end
  end

  def destroy
    @color.destroy!
    redirect_to admin_colors_path, success: 'Color was successfully destroyed.'
  end

  private

  def set_color
    @color = Color.find(params[:id])
  end

  def color_params
    params.require(:color).permit(:name, :code, :css_class, :season_type, :category_id)
  end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  def index
    if params[:season]
      @colors = Color.where(season_type: params[:season]).order(created_at: :asc)
    else
      @q = Color.ransack(params[:q])
      @colors = @q.result(distinct: true).order(created_at: :asc)
    end
  end

  def show
    @color = Color.find(params[:id])
  end

  def favorites
    @colors = current_user.favorite_colors.order(created_at: :desc)
  end

  def all_ranks
    @colors = Color.find(IncorrectAnswer.joins(quiz: :color).group(:color_id).order('count(color_id) desc').limit(10).pluck(:color_id))
  end

  def my_ranks
    @colors = Color.find(current_user.incorrect_answers.joins(quiz: :color).group(:color_id).order('count(color_id) desc').limit(10).pluck(:color_id))
  end
end

app/views/colors/_color.html.erb
<div class="container">
  <div class="row align-items-center justify-content-center g-0">
    <div class="col-lg-8 col-md-8 py-8 py-xl-0">
      <div class="card mb-2 border-0">
        <div class="card-body">
          <div class="container-fluid">
            <div class="row">
              <div class="col-2 color_sample d-flex align-items-center justify-content-center">
                <div class="circle">
                  <div class="circle-in <%= color.css_class %>"></div>
                </div>
              </div>
              <div class="col-8 color_name">
                <%= link_to color_path(color), class: "d-flex align-items-center" do %>
                  <%= color.name %>
                <% end %>
              </div>
              <div class="col-1 favorite_btn d-flex align-items-center justify-content-center">
                <%= render 'favorite_button', color: color %>
              </div>
              <div class="col-1 arrow d-flex align-items-center justify-content-center">
                <i class="fas fa-chevron-right"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/colors/_favorite.html.erb
<%= link_to favorites_path(color_id: color.id), id: "js-favorite-button-for-color-#{color.id}", method: :post, remote: true do %>
  <span class="favorite_btn"><i class="far fa-heart"></i></span>
<% end %>

app/views/colors/_favorite_button.html.erb
<% if current_user.favorite?(color) %>
  <%= render 'unfavorite', { color: color } %>
<% else %>
  <%= render 'favorite', { color: color } %>
<% end %>

app/views/colors/_tab_all.html.erb
<div class="container-fluid mb-3">
  <div class="row">
    <div class="col text-center tab_menu current">
      <%= link_to "ALL", colors_path %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "スプリング", colors_path(season: "spring") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "サマー", colors_path(season: "summer") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "オータム", colors_path(season: "autumn") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "ウィンター", colors_path(season: "winter") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "お気に入り", favorites_colors_path %>
    </div>
  </div>
</div>
<!-- search -->
<div class="container">
  <div class="row align-items-center justify-content-center">
    <div class="col-lg-8 col-md-8 mb-5 mt-1">
      <%= search_form_for @q, url: colors_path, class: 'd-flex align-items-center' do |f| %>
        <%= f.select :category_id_eq, [['ピンク', 1], ['レッド', 2], ['パープル', 3], ['ブルー', 4], ['グリーン', 5], ['イエロー', 6], ['オレンジ', 7], ['ブラウン', 8], ['ベージュ', 9], ['グレイ', 10], ['ホワイト', 11], ['ブラック', 12]], {include_blank: 'カテゴリ検索 ( 選択なし ）'}, class: 'form-select select_box me-2' %>
        <%= f.submit class: "btn search_btn ms-1 px-4" %>
      <% end %>
    </div>
  </div>
</div>

app/views/colors/_tab_autumn.html.erb
<div class="container-fluid mb-3">
  <div class="row">
    <div class="col text-center tab_menu">
      <%= link_to "ALL", colors_path %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "スプリング", colors_path(season: "spring") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "サマー", colors_path(season: "summer") %>
    </div>
    <div class="col text-center tab_menu current">
      <%= link_to "オータム", colors_path(season: "autumn") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "ウィンター", colors_path(season: "winter") %>
    </div>
    </div>
  </div>
</div>

app/views/colors/_tab_favorites.html.erb
<div class="container-fluid mb-3">
  <div class="row">
    <div class="col text-center tab_menu">
      <%= link_to "ALL", colors_path %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "スプリング", colors_path(season: "spring") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "サマー", colors_path(season: "summer") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "オータム", colors_path(season: "autumn") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "ウィンター", colors_path(season: "winter") %>
    </div>
    <div class="col text-center tab_menu current">
      <%= link_to "お気に入り", favorites_colors_path %>
    </div>
  </div>
</div>

app/views/colors/_tab_spring.html.erb
<div class="container-fluid mb-3">
  <div class="row">
    <div class="col text-center tab_menu">
      <%= link_to "ALL", colors_path %>
    </div>
    <div class="col text-center tab_menu current">
      <%= link_to "スプリング", colors_path(season: "spring") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "サマー", colors_path(season: "summer") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "オータム", colors_path(season: "autumn") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "ウィンター", colors_path(season: "winter") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "お気に入り", favorites_colors_path %>
    </div>
  </div>
</div>

app/views/colors/_tab_summer.html.erb
<div class="container-fluid mb-3">
  <div class="row">
    <div class="col text-center tab_menu">
      <%= link_to "ALL", colors_path %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "スプリング", colors_path(season: "spring") %>
    </div>
    <div class="col text-center tab_menu current">
      <%= link_to "サマー", colors_path(season: "summer") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "オータム", colors_path(season: "autumn") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "ウィンター", colors_path(season: "winter") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "お気に入り", favorites_colors_path %>
    </div>
  </div>
</div>

app/views/colors/_tab_winter.html.erb
<div class="container-fluid mb-3">
  <div class="row">
    <div class="col text-center tab_menu">
      <%= link_to "ALL", colors_path %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "スプリング", colors_path(season: "spring") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "サマー", colors_path(season: "summer") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "オータム", colors_path(season: "autumn") %>
    </div>
    <div class="col text-center tab_menu current">
      <%= link_to "ウィンター", colors_path(season: "winter") %>
    </div>
    <div class="col text-center tab_menu">
      <%= link_to "お気に入り", favorites_colors_path %>
    </div>
  </div>
</div>

app/views/colors/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(color_id: color.id)), id: "js-favorite-button-for-color-#{color.id}", method: :delete, remote: true do %>
  <span class="favorite_btn"><i class="fas fa-heart"></i></span>
<% end %>

app/views/colors/all_ranks.html.erb
<!-- title -->
<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="mt-5 text-center page_titile"><%= t '.title' %></h1>
    </div>
  </div>
</div>

<!-- tab -->
<div class="container-fluid mb-3">
  <div class="row">
    <div class="col text-center review_tab_menu current">
      <%= link_to "みんなのランキング", all_ranks_colors_path %>
    </div>
    <div class="col text-center review_tab_menu">
      <%= link_to "あなたのランキング", my_ranks_colors_path %>
    </div>
  </div>
</div>

<% @colors.each_with_index do |color, i| %>
  <div class="container">
    <div class="row align-items-center justify-content-center g-0">
      <div class="col-lg-8 col-md-8 py-8 py-xl-0">
        <div class="card mb-2 border-0">
          <div class="card-body">
            <div class="container-fluid">
              <div class="row">
                <div class="col-3 arrow d-flex align-items-center justify-content-center">
                  <%= i + 1 %>位
                </div>
                <div class="col-2 color_sample d-flex align-items-center justify-content-center">
                  <div class="circle">
                    <div class="circle-in <%= color.css_class %>"></div>
                  </div>
                </div>
                <div class="col-7 color_name">
                  <%= link_to color_path(color), class: "d-flex align-items-center" do %>
                    <%= color.name %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/colors/favorites.html.erb
<!-- title -->
<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="mt-5 text-center page_titile"><%= t '.title' %></h1>
    </div>
  </div>
</div>

<!-- tab -->
<% if params[:season] == "spring" %>
	<%= render 'tab_spring' %>
<% elsif params[:season] == "summer" %>
	<%= render 'tab_summer' %>
<% elsif params[:season] == "autumn" %>
	<%= render 'tab_autumn' %>
<% elsif params[:season] == "winter" %>
	<%= render 'tab_winter' %>
<% elsif request.url.include?('favorites') %>
	<%= render 'tab_favorites' %>
<% else %>
	<%= render 'tab_all' %> 
<% end %>

<% if @colors.present? %>
  <%= render @colors %>
<% else %>
  <div class="container mt-5">
    <div class="row">
      <div class="col d-flex justify-content-center no_result">
        <p><%= t('.no_result') %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/colors/my_ranks.html.erb
<!-- title -->
<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="mt-5 text-center page_titile"><%= t '.title' %></h1>
    </div>
  </div>
</div>

<!-- tab -->
<div class="container-fluid mb-3">
  <div class="row">
    <div class="col text-center review_tab_menu">
      <%= link_to "みんなのランキング", all_ranks_colors_path %>
    </div>
    <div class="col text-center review_tab_menu current">
      <%= link_to "あなたのランキング", my_ranks_colors_path %>
    </div>
  </div>
</div>

<% if @colors.present? %>
  <% @colors.each_with_index do |color, i| %>
    <div class="container">
      <div class="row align-items-center justify-content-center g-0">
        <div class="col-lg-8 col-md-8 py-8 py-xl-0">
          <div class="card mb-2 border-0">
            <div class="card-body">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-3 arrow d-flex align-items-center justify-content-center">
                    <%= i + 1 %>位
                  </div>
                  <div class="col-2 color_sample d-flex align-items-center justify-content-center">
                    <div class="circle">
                      <div class="circle-in <%= color.css_class %>"></div>
                    </div>
                  </div>
                  <div class="col-7 color_name">
                    <%= link_to color_path(color), class: "d-flex align-items-center" do %>
                        <%= color.name %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="container mt-5">
    <div class="row">
      <div class="col d-flex justify-content-center no_result">
        <p><%= t('.no_result') %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/colors/show.html.erb
<div class="color_box <%= @color.css_class %>"></div>
<div class="color_detail mt-5">
    <div class="d-flex flex-column bd-highlight mb-3 justify-content-center">
      <div class="p-2 bd-highlight d-flex justify-content-center color_show_name">
        <span class="me-3"><%= @color.name %><span>
        <%= render 'favorite_button', color: @color %>
      </div>
      <div class="p-2 bd-highlight d-flex justify-content-center color_show_code">
        <%= @color.code %>
      </div>
      <div class="p-2 bd-highlight d-flex justify-content-center color_show_season">
        <%= @color.season_type_i18n %>
      </div>
      <div class="p-2 bd-highlight d-flex justify-content-center align-items-center color_show_back_btn mt-4">
        <%= link_to "一覧に戻る", :back, class: "me-2"%>
      </div>
    </div>
</div>