config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'static_pages#top'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'contact_form', to: 'static_pages#contact_form'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'dashboard', to: 'dashboards#top'

  resources :users, only: %i[new create]
  resource :account, only: %i[show edit update destroy]

  resources :colors, only: %i[index show] do
    collection do
      get :favorites
    end
    collection do
      get :all_ranks
    end
    collection do
      get :my_ranks
    end
  end
  resources :quizzes, only: %i[index] do
    resources :incorrect_answers, only: %i[create update]
    resources :correct_answers, only: %i[create]
    collection do
      get :is_spring
    end
    collection do
      get :is_summer
    end
    collection do
      get :is_autumn
    end
    collection do
      get :is_winter
    end
    collection do
      get :base
    end
    collection do
      get :mistakes
    end
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]
  resources :trials, only: %i[index] 
  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users
    resources :colors
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::BaseController
  def index; end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def top
    @count = current_user.correct_answers.joins(quiz: :color).select(:color_id).distinct.count
    @colors = Color.all
  end
end

app/views/dashboards/top.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12">
      <div class="card py-3 user_profile fadeUp">
        <div class="card-body text-center">
          <div class="d-flex flex-column bd-highlight">
            <div class="p-2 bd-highlight pt-4">こんにちは!</div>
            <div class="p-2 bd-highlight pb-5"><%= current_user.name %>さん</div>
            <hr class="my-4">
            <div class="tweet-text", id="tweet-text">
              <div class="p-2 bd-highlight pt-5"><i class="fas fa-award me-2"></i>総クリア数(全<%= @colors.length %>色)</div>
              <div class="p-2 bd-highlight pt-2 pb-1">
                <p id="total_count", data-num="<%= @count %>">0</p><span id="total_count_colors">colors<span>
              </div>
            </div>
            <div class="p-2 bd-highlight pb-3">
              <!-- ツイートボタン --!>
              <div class="tweet" id="tweet">
                  <button id="twitter-share-button"><i class="fab fa-twitter me-1"></i>結果をシェア</button>
                  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-lg-3 mt-3">
      <%= link_to quizzes_path, class: "text-white" do %>
        <div class="card border-0 py-3 quiz fadeUp">
          <div class="card-body text-center text-white">
            <i class="far fa-check-circle text-white"></i>
              <span class="text-white">クイズに挑戦</span>
            <i class="fas fa-angle-right"></i>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-lg-3 mt-3">
      <%= link_to mistakes_quizzes_path, class: "text-white" do %>
        <div class="card border-0 py-3 review fadeUp">
          <div class="card-body text-center text-white">
            <i class="fas fa-pen text-white"></i>
              <span class="text-white">復習する</span>
            <i class="fas fa-angle-right"></i>
          </div>
        </div> 
      <% end %>
    </div>
    <div class="col-lg-3 mt-3">
      <%= link_to all_ranks_colors_path, class: "text-white" do %>
        <div class="card border-0 py-3 ranking fadeUp">
          <div class="card-body text-center text-white">
              <i class="fas fa-list-ol"></i>
              <span class="text-white">間違えやすい色</span>
            <i class="fas fa-angle-right"></i>
          </div>
        </div> 
      <% end %>
    </div>
    <div class="col-lg-3 mt-3">
      <%= link_to colors_path, class: "text-white" do %>
        <div class="card border-0 py-3 index fadeUp">
          <div class="card-body text-center text-white">
            <i class="fas fa-list-ul text-white"></i>
              <span class="text-white">色一覧</span>
            <i class="fas fa-angle-right"></i>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'dashboard' %>